# Generated by Django 2.2.4 on 2019-08-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vegit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vegit_date', models.DateField()),
                ('vegit_pred', models.FloatField()),
            ],
        ),
    ]
