# Generated by Django 2.2.4 on 2019-08-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vegit',
            name='vegit_date',
            field=models.CharField(max_length=40),
        ),
    ]
